//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hawk.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hawk.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 是否确定离开Hawk?  的本地化字符串。
        /// </summary>
        public static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【{0}】任务可能还没有保存，\\n【是】:保存任务并退出, \\n【否】：不保存退出，\\n【取消】:取消退出 的本地化字符串。
        /// </summary>
        public static string Closing2 {
            get {
                return ResourceManager.GetString("Closing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包含任何有关配置文件的任何信息，请检查 的本地化字符串。
        /// </summary>
        public static string ConfigNull {
            get {
                return ResourceManager.GetString("ConfigNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件加载 的本地化字符串。
        /// </summary>
        public static string ControlLoad {
            get {
                return ResourceManager.GetString("ControlLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据管理 的本地化字符串。
        /// </summary>
        public static string DataMgmt {
            get {
                return ResourceManager.GetString("DataMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统图标文件不存在 的本地化字符串。
        /// </summary>
        public static string IconNotExist {
            get {
                return ResourceManager.GetString("IconNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理长时间操作 的本地化字符串。
        /// </summary>
        public static string LongTask {
            get {
                return ResourceManager.GetString("LongTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块管理 的本地化字符串。
        /// </summary>
        public static string ModuleMgmt {
            get {
                return ResourceManager.GetString("ModuleMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源 的本地化字符串。
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已正常启动 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示信息 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
    }
}
